apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
spec:
  containers:
  - image: tuna/kubewatch:v0.0.3
    imagePullPolicy: Always
    name: kubewatch
    volumeMounts:
    - name: config-volume
      mountPath: /root
  restartPolicy: Always
  volumes:
  - name: config-volume
    configMap:
      name: kubewatch